### GENERAL VARIABLES ###
PAIRED_END: TRUE
CREATE_SUB_BAMS: FALSE
MAPPING_SUBFOLDER: ""


### INPUT FILES ###
# Path(s) to the directory or directories containing the trimmed fastq files to be mapped. To provide several directories, separate them with spaces.
 # If left blank, the workflow will assume the fastq files are in WORKFLOWS_OUTPUTS/DATA_CLEANING/DEMULT_TRIM, which is the path to our DATA_CLEANING workflow output files. 
TRIM_DIRS: ""

# Path to the reference file in fasta format (must end with .fa, .fas or .fasta).
REFERENCE: "../REFERENCE/Reference.fasta"

# Path to the bed file listing targeted zones. Optionnal: can be left blank ("").
BED: ""
BED_MIN_MEAN_COV: ""
BED_MIN_DIST: ""
BED_MIN_LENGTH: ""


### MAPPING PARAMETERS ###
MAPPER: "bwa_mem"
SEQUENCING_TECHNOLOGY: "ILLUMINA"
EXTRA_MAPPER_OPTIONS: "-t 4"

PICARD_MARKDUPLICATES_OPTIONS: "-MAX_FILE_HANDLES_FOR_READ_ENDS_MAP 1000"
PICARD_MARKDUPLICATES_JAVA_OPTIONS: ""

SAMTOOLS_INDEX_OPTIONS: "" # param "-c" is already included in the samtools command per default


### BAM FILTERING ###
## After the first mapping
REMOVE_DUP_MARKDUPLICATES: FALSE
REMOVE_DUP_UMI: FALSE
UMITOOLS_DEDUP_OPTIONS: ""

# options passed to 'samtools view'
SAMTOOLS_VIEW_FILTERS1: "-F 256 -F 2048 -f 2"

## After the remapping (options passed to 'samtools view'). If CREATE_SUB_BAMS is set to FALSE, leave blank (the command will not be called anyway)
SAMTOOLS_VIEW_FILTERS2: "-q 30"
